/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    manufacturers: Manufacturer;
    distributors: Distributor;
    'robot-series': RobotSery;
    robots: Robot;
    'use-cases': UseCase;
    deployments: Deployment;
    articles: Article;
    'article-placements': ArticlePlacement;
    media: Media;
    'content-route-registry': ContentRouteRegistry;
    'environment-marker': EnvironmentMarker;
    'audit-upload-sessions': AuditUploadSession;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    'robot-series': RobotSeriesSelect<false> | RobotSeriesSelect<true>;
    robots: RobotsSelect<false> | RobotsSelect<true>;
    'use-cases': UseCasesSelect<false> | UseCasesSelect<true>;
    deployments: DeploymentsSelect<false> | DeploymentsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-placements': ArticlePlacementsSelect<false> | ArticlePlacementsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'content-route-registry': ContentRouteRegistrySelect<false> | ContentRouteRegistrySelect<true>;
    'environment-marker': EnvironmentMarkerSelect<false> | EnvironmentMarkerSelect<true>;
    'audit-upload-sessions': AuditUploadSessionsSelect<false> | AuditUploadSessionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  role: 'content-reader' | 'content-draft-writer' | 'content-publisher' | 'platform-admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  featuredRank?: number | null;
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  name: string;
  nameJa?: string | null;
  summary: string;
  description: string;
  country: string;
  hqCity?: string | null;
  headquarters?: {
    lat?: number | null;
    lng?: number | null;
  };
  foundedYear?: number | null;
  companyType: 'manufacturer' | 'distributor' | 'integrator' | 'ai-os' | 'research';
  companyStatus?: ('active' | 'stealth' | 'acquired' | 'inactive') | null;
  japanPresence: 'office' | 'distributor' | 'partner' | 'remote' | 'none' | 'unknown';
  website: string;
  contactUrl?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  /**
   * Logo images (symbol / wordmark / combined variants, each optional). Shown at the top of the manufacturer detail page.
   */
  logos?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  /**
   * Domestic distributors. Shown in the "Domestic distributors" section of the manufacturer detail page.
   */
  domesticDistributors?:
    | {
        name: string;
        website?: string | null;
        sourceUrl?: string | null;
        /**
         * The date this distributor listing was last checked. Not shown publicly — kept for internal reference.
         */
        checkedAt?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  distributorNote?: string | null;
  supportNote?: string | null;
  procurementNote?: string | null;
  vendorRiskNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  summary: string;
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  name: string;
  nameJa?: string | null;
  website?: string | null;
  providerType: 'maker-direct' | 'reseller' | 'other';
  handledManufacturerIds: (number | Manufacturer)[];
  handledRobotIds?: (number | Robot)[] | null;
  acquisitionMethods: ('purchase' | 'lease' | 'raas' | 'subscription' | 'inquiry')[];
  inquiryUrl?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots".
 */
export interface Robot {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  summary: string;
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  name: string;
  nameJa?: string | null;
  manufacturerId: number | Manufacturer;
  seriesId?: (number | null) | RobotSery;
  category: 'humanoid' | 'general-purpose-robot' | 'upper-body-humanoid' | 'mobile-manipulator' | 'other';
  description?: string | null;
  featuredRank?: number | null;
  deploymentStage:
    'concept' | 'prototype' | 'pilot' | 'limited-production' | 'production' | 'internal-use' | 'discontinued';
  supersededById?: (number | null) | Robot;
  /**
   * Spec values, keyed by item name. Shown in the "Specifications" sections of the robot detail page.
   */
  specs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  procurementModels?:
    ('purchase' | 'lease' | 'raas' | 'subscription' | 'partner-program' | 'not-for-sale' | 'inquiry')[] | null;
  priceOffers?:
    | {
        channel: 'manufacturer-public' | 'authorized-distributor-public';
        display: string;
        amount?: number | null;
        currency?: string | null;
        taxStatus?: ('included' | 'excluded' | 'unknown') | null;
        variant?: string | null;
        sellerName?: string | null;
        sourceUrl: string;
        id?: string | null;
      }[]
    | null;
  loadRatings?:
    | {
        scope: 'single-arm' | 'dual-arm' | 'whole-body' | 'carrier' | 'manufacturer-wording';
        rating: 'rated' | 'maximum' | 'unspecified';
        kg: number;
        condition?: string | null;
        variant?: string | null;
        sourceUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Source URLs backing each spec value. Shown as the citation links attached to each spec row on the robot detail page.
   */
  fieldEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  usageExampleSourceUrls?: string[] | null;
  japanAvailability:
    'official-japan' | 'distributor-japan' | 'inquiry-required' | 'import-only' | 'unavailable' | 'unknown';
  distributorJapan?: string | null;
  supportNote?: string | null;
  /**
   * Images by role (all optional). Shown in the image gallery on the robot detail page.
   */
  images?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  industryTags?: string[] | null;
  taskTags?: string[] | null;
  /**
   * Comparison info (strengths / constraints / fit). Shown on the /compare page, not the robot detail page. Scheduled for a future rework, but should still be filled in for now.
   */
  comparison?: {
    strengths?: string[] | null;
    constraints?: string[] | null;
    bestFit?: string[] | null;
    notFit?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robot-series".
 */
export interface RobotSery {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  summary: string;
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  name: string;
  nameJa?: string | null;
  manufacturerId: number | Manufacturer;
  description?: string | null;
  /**
   * Images by role (all optional). Not shown on any public page yet — there is currently no dedicated page for a robot series on its own.
   */
  images?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  industryTags?: string[] | null;
  taskTags?: string[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases".
 */
export interface UseCase {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  summary: string;
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  title: string;
  titleJa?: string | null;
  subtitle?: string | null;
  maturityLevel: 'early-stage' | 'pilot-phase' | 'production-ready';
  /**
   * Buyer readiness. Not currently shown anywhere on the public site — used for internal classification only.
   */
  buyerReadiness?: ('initial-adoption' | 'requires-poc' | 'limited-today') | null;
  environment: 'indoor-controlled' | 'indoor-semi-controlled' | 'outdoor' | 'mixed' | 'hazardous';
  requiredCapabilities: (
    'mobility' | 'manipulation' | 'perception' | 'autonomy' | 'communication' | 'data-capture' | 'integration'
  )[];
  primaryIndustry: string;
  industryTags?: string[] | null;
  taskTags?: string[] | null;
  atAGlance?: {
    whereFits?: string | null;
    whereDoesNotFit?: string | null;
    mustBeTrue?: string | null;
  };
  overview: string;
  whyItMatters: string;
  capabilityNotes?: {
    mobility?: string | null;
    manipulation?: string | null;
    perception?: string | null;
    autonomy?: string | null;
    communication?: string | null;
    integration?: string | null;
  };
  environmentRequirements?: string | null;
  whyHardToday?: string | null;
  japanDeploymentConditions?: string | null;
  /**
   * Candidate robots. Shown in the "Candidate robots" section of the use case detail page — but currently **only rows with a specific robot render; series-only rows do not appear yet**.
   */
  candidateRobots?:
    | {
        robotId?: (number | null) | Robot;
        seriesId?: (number | null) | RobotSery;
        fit: 'strong' | 'possible' | 'watch';
        basis:
          | 'deployment'
          | 'adjacent-deployment'
          | 'official-use-case'
          | 'product-capability'
          | 'market-signal'
          | 'editorial-watch';
        evidenceDeploymentIds?: (number | Deployment)[] | null;
        evidenceSourceUrls?: string[] | null;
        reason: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployments".
 */
export interface Deployment {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  summary: string;
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  manufacturerId: number | Manufacturer;
  robotId?: (number | null) | Robot;
  customer: string;
  siteName?: string | null;
  country: string;
  location: {
    lat: number;
    lng: number;
  };
  status: 'announced' | 'pilot' | 'production' | 'ended' | 'unknown';
  startedAt?: string | null;
  relatedUseCaseIds?: (number | UseCase)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  summary: string;
  reliability?: ('verified' | 'official' | 'reported' | 'estimated') | null;
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    /**
     * The date this source was published. Month- or year-only is fine when the exact day is unknown (e.g. 2025-05). Not shown in the general source list, but shown if this source's URL is also referenced in a "Usage examples" section.
     */
    publishedAt?: string | null;
    /**
     * The date this source was last checked. Shown on the public source list as "Checked …".
     */
    checkedAt: string;
    reliability: 'verified' | 'official' | 'reported' | 'estimated';
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * The date this record's content should next be reviewed. Not shown publicly — used to schedule internal fact-checks.
   */
  nextReviewBy?: string | null;
  heroImage?: {
    src?: string | null;
    alt?: string | null;
    credit?: string | null;
    sourceUrl?: string | null;
    rights?: {
      status?:
        | (
            | 'own'
            | 'licensed'
            | 'commercial-permitted'
            | 'reference-attributed'
            | 'permission-requested'
            | 'prototype-only'
            | 'blocked'
          )
        | null;
      sourceType?:
        ('own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown') | null;
      /**
       * The date this image's rights status was last confirmed. Not shown publicly — for internal rights tracking.
       */
      checkedAt?: string | null;
      rightsHolder?: string | null;
      licenseUrl?: string | null;
      permissionNote?: string | null;
    };
    aspectRatio?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noindex?: boolean | null;
  };
  title: string;
  titleJa?: string | null;
  category: 'news' | 'interview' | 'company-report' | 'analysis' | 'policy';
  type:
    | 'analysis'
    | 'deployment-report'
    | 'interview'
    | 'event-report'
    | 'policy-update'
    | 'case-study'
    | 'news-brief'
    | 'tech-update'
    | 'market-analysis'
    | 'manufacturer-guide'
    | 'robot-guide'
    | 'basics-guide';
  section: 'digest' | 'deployment' | 'business' | 'tech' | 'policy' | 'entertainment';
  contentKind?: ('editorial' | 'sample' | 'sponsored') | null;
  /**
   * The article's publish date. Shown on the article card and detail page.
   */
  publishedAt: string;
  author?: string | null;
  industryTags?: string[] | null;
  regionTags?: string[] | null;
  themeTags?: string[] | null;
  whyItMatters: string;
  keyTakeaways?: string[] | null;
  featured?: boolean | null;
  relatedRobotIds?: (number | Robot)[] | null;
  relatedManufacturerIds?: (number | Manufacturer)[] | null;
  relatedUseCaseIds?: (number | UseCase)[] | null;
  /**
   * Article body (Markdown). When the article type is "Manufacturer guide", use the dedicated field below (manufacturerGuideContent) instead of this one.
   */
  body?: string | null;
  /**
   * Manufacturer-guide-only content (company overview, lineup, deployment status, procurement channels, FAQ, etc.). Used only when the article type is "Manufacturer guide" — rendered as the corresponding sections on the article detail page.
   */
  manufacturerGuideContent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-placements".
 */
export interface ArticlePlacement {
  id: number;
  /**
   * Admin公開UIの競合制御marker（lib/payload/adminPublishIntent.ts）。運用メタデータで、コンテンツではない。値はhookだけが書き、公開時にcanonical contentから除外される。
   */
  adminPublishIntentToken?: string | null;
  stableId: string;
  slug: string;
  previousSlugs?: string[] | null;
  lifecycleStatus: 'active' | 'archived';
  surface: 'reports-index';
  slot: 'hero' | 'feature';
  articleId: number | Article;
  order: number;
  kind?: ('editorial' | 'sample' | 'sponsored' | 'house') | null;
  sponsor?: {
    name?: string | null;
    url?: string | null;
    disclosure?: string | null;
    campaignId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  stableId: string;
  alt: string;
  rights: {
    status:
      | 'own'
      | 'licensed'
      | 'commercial-permitted'
      | 'reference-attributed'
      | 'permission-requested'
      | 'prototype-only'
      | 'blocked';
    sourceType: 'own' | 'manufacturer-official' | 'partner-official' | 'press-release' | 'third-party' | 'unknown';
    /**
     * The date this file's rights status was last confirmed. Not shown publicly — for internal rights tracking.
     */
    checkedAt: string;
    rightsHolder?: string | null;
    licenseUrl?: string | null;
    permissionNote?: string | null;
  };
  credit?: string | null;
  sourceUrl?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-route-registry".
 */
export interface ContentRouteRegistry {
  id: number;
  namespace: string;
  slug: string;
  ownerCollection: 'robots' | 'robot-series';
  ownerStableId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "environment-marker".
 */
export interface EnvironmentMarker {
  id: number;
  environment: 'preview' | 'production';
  /**
   * Always 1. Unique constraint caps this table at a single row.
   */
  singleton: number;
  /**
   * Highest baseline generation ever restored into this database. Older generations are refused.
   */
  lastRestoredBaselineGeneration?: number | null;
  /**
   * baselineRunId of the most recently applied restore (audit trail).
   */
  lastRestoredBaselineRunId?: string | null;
  /**
   * ISO timestamp of the most recently applied restore.
   */
  lastRestoredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-upload-sessions".
 */
export interface AuditUploadSession {
  id: number;
  /**
   * crypto.randomBytes由来の推測不能な値。Payloadの自動採番idは連番で推測可能なため、これをURL path paramとして使う（自動採番idは使わない）。
   */
  sessionId: string;
  /**
   * CLI側が生成したcorrelation ID。Step 2/3/DELETEで一致を要求する。
   */
  requestId: string;
  /**
   * canonicalJson(manifest)のsha256。session全体がどのmanifestに紐づくかの記録。
   */
  manifestSha256: string;
  /**
   * manifest.storage.objectKey。許可prefix判定の基準値。
   */
  baselineObjectKey: string;
  /**
   * manifest.provenance.baselineRunId。completion markerへ書く値はここに保存した値を使う（Step 3のrequest bodyの値をそのまま信用しない——一致しなければ拒否する）。
   */
  baselineRunId: string;
  environment: 'preview' | 'production';
  /**
   * 署名検証済みmanifestから導出した許可object一覧（client申告値ではない）。
   */
  allowedObjects: {
    objectKey: string;
    /**
     * signature bundle entryだけnull（manifestに事前宣言されたsha256が無いため。`lib/payload/auditUploadSession.ts`のコメント参照）。それ以外は必ず設定される。
     */
    sha256?: string | null;
    /**
     * manifestが値を持つ場合（media）だけ設定する。snapshot本体・signature bundleはmanifestにsize欄が無いためnull——sha256一致だけがそれらの正当性の根拠になる（sha256が実質的に長さも含めて内容を一意に決める）。
     */
    size?: number | null;
    uploaded: boolean;
    /**
     * media entryだけ設定する（`MediaInventoryEntry.stableId`）。Step 3で`manifest.mediaInventory`と同じ形を再構築し、既存exporterと同じ`sha256Hex(canonicalJson(mediaInventory))`でmediaInventorySha256を計算するために必要。
     */
    stableId?: string | null;
    /**
     * media entryだけ設定する。
     */
    filename?: string | null;
    /**
     * media entryだけ設定する。
     */
    mimeType?: string | null;
    id?: string | null;
  }[];
  /**
   * completedになったsessionはStep 2/3を二度と受け付けない（replay防止）。期限切れ判定は`expiresAt`との比較で別途行う（statusをexpiredへ書き換える専用処理は持たない）。
   */
  status: 'pending' | 'completed';
  /**
   * ISO date。この時刻を過ぎたpending sessionはStep 2/3を拒否し、cleanup対象になる。
   */
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user?: (number | null) | Admin;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  manufacturers?: {
    /**
     * Allow clients to find manufacturers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create manufacturers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update manufacturers.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete manufacturers.
     */
    delete?: boolean | null;
  };
  distributors?: {
    /**
     * Allow clients to find distributors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create distributors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update distributors.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete distributors.
     */
    delete?: boolean | null;
  };
  robotSeries?: {
    /**
     * Allow clients to find robot-series.
     */
    find?: boolean | null;
    /**
     * Allow clients to create robot-series.
     */
    create?: boolean | null;
    /**
     * Allow clients to update robot-series.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete robot-series.
     */
    delete?: boolean | null;
  };
  robots?: {
    /**
     * Allow clients to find robots.
     */
    find?: boolean | null;
    /**
     * Allow clients to create robots.
     */
    create?: boolean | null;
    /**
     * Allow clients to update robots.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete robots.
     */
    delete?: boolean | null;
  };
  useCases?: {
    /**
     * Allow clients to find use-cases.
     */
    find?: boolean | null;
    /**
     * Allow clients to create use-cases.
     */
    create?: boolean | null;
    /**
     * Allow clients to update use-cases.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete use-cases.
     */
    delete?: boolean | null;
  };
  deployments?: {
    /**
     * Allow clients to find deployments.
     */
    find?: boolean | null;
    /**
     * Allow clients to create deployments.
     */
    create?: boolean | null;
    /**
     * Allow clients to update deployments.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete deployments.
     */
    delete?: boolean | null;
  };
  articles?: {
    /**
     * Allow clients to find articles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create articles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update articles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete articles.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'distributors';
        value: number | Distributor;
      } | null)
    | ({
        relationTo: 'robot-series';
        value: number | RobotSery;
      } | null)
    | ({
        relationTo: 'robots';
        value: number | Robot;
      } | null)
    | ({
        relationTo: 'use-cases';
        value: number | UseCase;
      } | null)
    | ({
        relationTo: 'deployments';
        value: number | Deployment;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-placements';
        value: number | ArticlePlacement;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'content-route-registry';
        value: number | ContentRouteRegistry;
      } | null)
    | ({
        relationTo: 'environment-marker';
        value: number | EnvironmentMarker;
      } | null)
    | ({
        relationTo: 'audit-upload-sessions';
        value: number | AuditUploadSession;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  featuredRank?: T;
  nextReviewBy?: T;
  name?: T;
  nameJa?: T;
  summary?: T;
  description?: T;
  country?: T;
  hqCity?: T;
  headquarters?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  foundedYear?: T;
  companyType?: T;
  companyStatus?: T;
  japanPresence?: T;
  website?: T;
  contactUrl?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  logos?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  reliability?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  domesticDistributors?:
    | T
    | {
        name?: T;
        website?: T;
        sourceUrl?: T;
        checkedAt?: T;
        note?: T;
        id?: T;
      };
  distributorNote?: T;
  supportNote?: T;
  procurementNote?: T;
  vendorRiskNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  summary?: T;
  reliability?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  nextReviewBy?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  name?: T;
  nameJa?: T;
  website?: T;
  providerType?: T;
  handledManufacturerIds?: T;
  handledRobotIds?: T;
  acquisitionMethods?: T;
  inquiryUrl?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robot-series_select".
 */
export interface RobotSeriesSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  summary?: T;
  reliability?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  nextReviewBy?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  name?: T;
  nameJa?: T;
  manufacturerId?: T;
  description?: T;
  images?: T;
  industryTags?: T;
  taskTags?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots_select".
 */
export interface RobotsSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  summary?: T;
  reliability?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  nextReviewBy?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  name?: T;
  nameJa?: T;
  manufacturerId?: T;
  seriesId?: T;
  category?: T;
  description?: T;
  featuredRank?: T;
  deploymentStage?: T;
  supersededById?: T;
  specs?: T;
  procurementModels?: T;
  priceOffers?:
    | T
    | {
        channel?: T;
        display?: T;
        amount?: T;
        currency?: T;
        taxStatus?: T;
        variant?: T;
        sellerName?: T;
        sourceUrl?: T;
        id?: T;
      };
  loadRatings?:
    | T
    | {
        scope?: T;
        rating?: T;
        kg?: T;
        condition?: T;
        variant?: T;
        sourceUrl?: T;
        id?: T;
      };
  fieldEvidence?: T;
  usageExampleSourceUrls?: T;
  japanAvailability?: T;
  distributorJapan?: T;
  supportNote?: T;
  images?: T;
  industryTags?: T;
  taskTags?: T;
  comparison?:
    | T
    | {
        strengths?: T;
        constraints?: T;
        bestFit?: T;
        notFit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  summary?: T;
  reliability?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  nextReviewBy?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  title?: T;
  titleJa?: T;
  subtitle?: T;
  maturityLevel?: T;
  buyerReadiness?: T;
  environment?: T;
  requiredCapabilities?: T;
  primaryIndustry?: T;
  industryTags?: T;
  taskTags?: T;
  atAGlance?:
    | T
    | {
        whereFits?: T;
        whereDoesNotFit?: T;
        mustBeTrue?: T;
      };
  overview?: T;
  whyItMatters?: T;
  capabilityNotes?:
    | T
    | {
        mobility?: T;
        manipulation?: T;
        perception?: T;
        autonomy?: T;
        communication?: T;
        integration?: T;
      };
  environmentRequirements?: T;
  whyHardToday?: T;
  japanDeploymentConditions?: T;
  candidateRobots?:
    | T
    | {
        robotId?: T;
        seriesId?: T;
        fit?: T;
        basis?: T;
        evidenceDeploymentIds?: T;
        evidenceSourceUrls?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployments_select".
 */
export interface DeploymentsSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  summary?: T;
  reliability?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  nextReviewBy?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  manufacturerId?: T;
  robotId?: T;
  customer?: T;
  siteName?: T;
  country?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  status?: T;
  startedAt?: T;
  relatedUseCaseIds?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  summary?: T;
  reliability?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        checkedAt?: T;
        reliability?: T;
        note?: T;
        id?: T;
      };
  nextReviewBy?: T;
  heroImage?:
    | T
    | {
        src?: T;
        alt?: T;
        credit?: T;
        sourceUrl?: T;
        rights?:
          | T
          | {
              status?: T;
              sourceType?: T;
              checkedAt?: T;
              rightsHolder?: T;
              licenseUrl?: T;
              permissionNote?: T;
            };
        aspectRatio?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
      };
  title?: T;
  titleJa?: T;
  category?: T;
  type?: T;
  section?: T;
  contentKind?: T;
  publishedAt?: T;
  author?: T;
  industryTags?: T;
  regionTags?: T;
  themeTags?: T;
  whyItMatters?: T;
  keyTakeaways?: T;
  featured?: T;
  relatedRobotIds?: T;
  relatedManufacturerIds?: T;
  relatedUseCaseIds?: T;
  body?: T;
  manufacturerGuideContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-placements_select".
 */
export interface ArticlePlacementsSelect<T extends boolean = true> {
  adminPublishIntentToken?: T;
  stableId?: T;
  slug?: T;
  previousSlugs?: T;
  lifecycleStatus?: T;
  surface?: T;
  slot?: T;
  articleId?: T;
  order?: T;
  kind?: T;
  sponsor?:
    | T
    | {
        name?: T;
        url?: T;
        disclosure?: T;
        campaignId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  stableId?: T;
  alt?: T;
  rights?:
    | T
    | {
        status?: T;
        sourceType?: T;
        checkedAt?: T;
        rightsHolder?: T;
        licenseUrl?: T;
        permissionNote?: T;
      };
  credit?: T;
  sourceUrl?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-route-registry_select".
 */
export interface ContentRouteRegistrySelect<T extends boolean = true> {
  namespace?: T;
  slug?: T;
  ownerCollection?: T;
  ownerStableId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "environment-marker_select".
 */
export interface EnvironmentMarkerSelect<T extends boolean = true> {
  environment?: T;
  singleton?: T;
  lastRestoredBaselineGeneration?: T;
  lastRestoredBaselineRunId?: T;
  lastRestoredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-upload-sessions_select".
 */
export interface AuditUploadSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  requestId?: T;
  manifestSha256?: T;
  baselineObjectKey?: T;
  baselineRunId?: T;
  environment?: T;
  allowedObjects?:
    | T
    | {
        objectKey?: T;
        sha256?: T;
        size?: T;
        uploaded?: T;
        stableId?: T;
        filename?: T;
        mimeType?: T;
        id?: T;
      };
  status?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  manufacturers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  distributors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  robotSeries?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  robots?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  useCases?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  deployments?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  articles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  announcementBanner?: {
    enabled?: boolean | null;
    message?: string | null;
    url?: string | null;
  };
  /**
   * The point in time the listing counts are accurate as of (e.g. "July 2026"). Day-level precision is not required. **Not shown anywhere on the public site yet** — used only for export/import consistency checks.
   */
  dataAsOf?: string | null;
  /**
   * Maximum number of articles shown in the hero/feature slots on the article index page. Affects how many items appear on the home page and the article index page.
   */
  articleIndexPlacementLimits?: {
    hero?: number | null;
    feature?: number | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  announcementBanner?:
    | T
    | {
        enabled?: T;
        message?: T;
        url?: T;
      };
  dataAsOf?: T;
  articleIndexPlacementLimits?:
    | T
    | {
        hero?: T;
        feature?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}