import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "manufacturers_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "manufacturers_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "manufacturers_domestic_distributors" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "manufacturers" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "manufacturers" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_manufacturers_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_manufacturers_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_manufacturers_v_version_domestic_distributors" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "distributors_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "distributors_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "distributors" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "distributors" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_distributors_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_distributors_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "robot_series_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "robot_series_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "robot_series" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "robot_series" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_robot_series_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_robot_series_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "robots_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "robots_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "robots" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "robots" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_robots_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_robots_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_robots_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_robots_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "use_cases_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "use_cases_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "use_cases" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "use_cases" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_use_cases_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_use_cases_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_use_cases_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_use_cases_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "deployments_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "deployments_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "deployments" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "deployments" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_deployments_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_deployments_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "articles_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "articles_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "articles" ALTER COLUMN "next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "articles" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "articles" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_articles_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE varchar;
  ALTER TABLE "_articles_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_articles_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE varchar;
  ALTER TABLE "_articles_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE varchar;
  ALTER TABLE "_articles_v" ALTER COLUMN "version_published_at" SET DATA TYPE varchar;
  ALTER TABLE "media" ALTER COLUMN "rights_checked_at" SET DATA TYPE varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "manufacturers_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "manufacturers_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "manufacturers_domestic_distributors" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "manufacturers" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "manufacturers" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_manufacturers_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_manufacturers_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_manufacturers_v_version_domestic_distributors" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "distributors_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "distributors_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "distributors" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "distributors" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_distributors_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_distributors_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robot_series_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robot_series_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robot_series" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robot_series" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robot_series_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robot_series_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robots_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robots_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robots" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "robots" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robots_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robots_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robots_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_robots_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "use_cases_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "use_cases_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "use_cases" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "use_cases" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_use_cases_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_use_cases_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_use_cases_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_use_cases_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "deployments_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "deployments_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "deployments" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "deployments" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_deployments_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_deployments_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "articles_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "articles_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "articles" ALTER COLUMN "next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "articles" ALTER COLUMN "hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "articles" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_articles_v_version_sources" ALTER COLUMN "published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_articles_v_version_sources" ALTER COLUMN "checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_articles_v" ALTER COLUMN "version_next_review_by" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_articles_v" ALTER COLUMN "version_hero_image_rights_checked_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "_articles_v" ALTER COLUMN "version_published_at" SET DATA TYPE timestamp(3) with time zone;
  ALTER TABLE "media" ALTER COLUMN "rights_checked_at" SET DATA TYPE timestamp(3) with time zone;`)
}
