import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * 手書き追記（自動生成部分ではない）: `images`/`logos`をJSON列から構造化列へ移す際、
 * 自動生成された`up()`は新しい列を追加した直後に旧JSON列を`DROP COLUMN`するだけで、
 * 既存データを新しい列へ複製しない。ロボット画像・メーカーロゴの実データを失わないため、
 * `DROP COLUMN`の直前に、JSONの各roleキー・各サブフィールドを対応する新しい列へ
 * `UPDATE ... SET`でコピーするSQLをここで組み立てる（役割×サブフィールド数が多く手書きだと
 * 転記ミスの危険が大きいため、`ADD COLUMN`と同じ命名規則からプログラムで生成する）。
 */
interface ImageBackfillSpec {
  table: string;
  jsonColumn: string;
  roles: readonly string[];
}

const ROBOT_IMAGE_ROLES = ['hero', 'transparent', 'side', 'inOperation', 'scale', 'endEffector', 'mobility'] as const;
const MANUFACTURER_LOGO_ROLES = ['symbol', 'wordmark', 'combined'] as const;

/** camelCase field/roleキーをsnake_caseの列名断片へ（Payload/drizzleの列命名規則と一致させる）。 */
function toSnakeCase(value: string): string {
  return value.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function imageAssetBackfillAssignments(jsonColumn: string, role: string): string[] {
  const prefix = `${jsonColumn}_${toSnakeCase(role)}`;
  const rolePath = `"${jsonColumn}"->'${role}'`;
  return [
    `"${prefix}_src" = ${rolePath}->>'src'`,
    `"${prefix}_alt" = ${rolePath}->>'alt'`,
    `"${prefix}_credit" = ${rolePath}->>'credit'`,
    `"${prefix}_source_url" = ${rolePath}->>'sourceUrl'`,
    `"${prefix}_rights_status" = (${rolePath}->'rights'->>'status')::"rights_status"`,
    `"${prefix}_rights_source_type" = (${rolePath}->'rights'->>'sourceType')::"rights_source_type"`,
    `"${prefix}_rights_checked_at" = ${rolePath}->'rights'->>'checkedAt'`,
    `"${prefix}_rights_rights_holder" = ${rolePath}->'rights'->>'rightsHolder'`,
    `"${prefix}_rights_license_url" = ${rolePath}->'rights'->>'licenseUrl'`,
    `"${prefix}_rights_permission_note" = ${rolePath}->'rights'->>'permissionNote'`,
    `"${prefix}_aspect_ratio" = (${rolePath}->>'aspectRatio')::numeric`,
  ];
}

function imageBackfillStatement(spec: ImageBackfillSpec): string {
  const assignments = spec.roles.flatMap((role) => imageAssetBackfillAssignments(spec.jsonColumn, role));
  return `UPDATE "${spec.table}" SET ${assignments.join(', ')} WHERE "${spec.jsonColumn}" IS NOT NULL;`;
}

const IMAGE_BACKFILL_SPECS: ImageBackfillSpec[] = [
  { table: 'manufacturers', jsonColumn: 'logos', roles: MANUFACTURER_LOGO_ROLES },
  { table: '_manufacturers_v', jsonColumn: 'version_logos', roles: MANUFACTURER_LOGO_ROLES },
  { table: 'robot_series', jsonColumn: 'images', roles: ROBOT_IMAGE_ROLES },
  { table: '_robot_series_v', jsonColumn: 'version_images', roles: ROBOT_IMAGE_ROLES },
  { table: 'robots', jsonColumn: 'images', roles: ROBOT_IMAGE_ROLES },
  { table: '_robots_v', jsonColumn: 'version_images', roles: ROBOT_IMAGE_ROLES },
];

const IMAGE_FIELDS_BACKFILL_SQL = IMAGE_BACKFILL_SPECS.map(imageBackfillStatement).join('\n');

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  ALTER TABLE "manufacturers" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "manufacturers" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "version_hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "distributors" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "distributors" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "version_hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "robot_series" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "robot_series" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "version_hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "robots" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "robots" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "_robots_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "version_hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "_robots_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "deployments" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "deployments" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "version_hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "articles" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "articles" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "_articles_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."rights_status" USING "version_hero_image_rights_status"::text::"public"."rights_status";
  ALTER TABLE "_articles_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."rights_source_type";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_src" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_alt" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_credit" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_source_url" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_rights_status" "rights_status";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_rights_source_type" "rights_source_type";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_rights_checked_at" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_rights_rights_holder" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_rights_license_url" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_rights_permission_note" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_symbol_aspect_ratio" numeric;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_src" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_alt" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_credit" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_source_url" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_rights_status" "rights_status";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_rights_source_type" "rights_source_type";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_rights_checked_at" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_rights_rights_holder" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_rights_license_url" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_rights_permission_note" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_wordmark_aspect_ratio" numeric;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_src" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_alt" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_credit" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_source_url" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_rights_status" "rights_status";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_rights_source_type" "rights_source_type";
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_rights_checked_at" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_rights_rights_holder" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_rights_license_url" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_rights_permission_note" varchar;
  ALTER TABLE "manufacturers" ADD COLUMN "logos_combined_aspect_ratio" numeric;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_src" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_alt" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_credit" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_source_url" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_rights_status" "rights_status";
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_rights_source_type" "rights_source_type";
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_rights_checked_at" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_rights_rights_holder" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_rights_license_url" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_rights_permission_note" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_symbol_aspect_ratio" numeric;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_src" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_alt" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_credit" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_source_url" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_rights_status" "rights_status";
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_rights_source_type" "rights_source_type";
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_rights_checked_at" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_rights_rights_holder" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_rights_license_url" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_rights_permission_note" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_wordmark_aspect_ratio" numeric;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_src" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_alt" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_credit" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_source_url" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_rights_status" "rights_status";
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_rights_source_type" "rights_source_type";
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_rights_checked_at" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_rights_rights_holder" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_rights_license_url" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_rights_permission_note" varchar;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos_combined_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_hero_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_transparent_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_side_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_side_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_side_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_in_operation_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_scale_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_end_effector_aspect_ratio" numeric;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_src" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_alt" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_credit" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_source_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_rights_status" "rights_status";
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_rights_source_type" "rights_source_type";
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_rights_checked_at" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_rights_rights_holder" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_rights_license_url" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_rights_permission_note" varchar;
  ALTER TABLE "robot_series" ADD COLUMN "images_mobility_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_hero_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_transparent_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_side_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_in_operation_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_scale_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_end_effector_aspect_ratio" numeric;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_src" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_alt" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_credit" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_source_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_rights_status" "rights_status";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_rights_source_type" "rights_source_type";
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_rights_checked_at" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_rights_rights_holder" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_rights_license_url" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_rights_permission_note" varchar;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images_mobility_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_hero_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_hero_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_hero_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_hero_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_transparent_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_transparent_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_transparent_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_side_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_side_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_side_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_side_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_in_operation_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_scale_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_scale_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_scale_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_scale_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_end_effector_aspect_ratio" numeric;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_src" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_alt" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_credit" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_source_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_rights_status" "rights_status";
  ALTER TABLE "robots" ADD COLUMN "images_mobility_rights_source_type" "rights_source_type";
  ALTER TABLE "robots" ADD COLUMN "images_mobility_rights_checked_at" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_rights_rights_holder" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_rights_license_url" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_rights_permission_note" varchar;
  ALTER TABLE "robots" ADD COLUMN "images_mobility_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_hero_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_transparent_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_side_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_in_operation_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_scale_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_end_effector_aspect_ratio" numeric;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_src" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_alt" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_credit" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_source_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_rights_status" "rights_status";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_rights_source_type" "rights_source_type";
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_rights_checked_at" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_rights_rights_holder" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_rights_license_url" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_rights_permission_note" varchar;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images_mobility_aspect_ratio" numeric;`)

  // 手書き追記: 新しい列を追加した直後・旧JSON列をDROPする前に、既存データを複製する。
  await db.execute(sql.raw(IMAGE_FIELDS_BACKFILL_SQL))

  await db.execute(sql`
  ALTER TABLE "manufacturers" DROP COLUMN "logos";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos";
  ALTER TABLE "robot_series" DROP COLUMN "images";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images";
  ALTER TABLE "robots" DROP COLUMN "images";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images";
  DROP TYPE "public"."enum_manufacturers_hero_image_rights_status";
  DROP TYPE "public"."enum_manufacturers_hero_image_rights_source_type";
  DROP TYPE "public"."enum__manufacturers_v_version_hero_image_rights_status";
  DROP TYPE "public"."enum__manufacturers_v_version_hero_image_rights_source_type";
  DROP TYPE "public"."enum_distributors_hero_image_rights_status";
  DROP TYPE "public"."enum_distributors_hero_image_rights_source_type";
  DROP TYPE "public"."enum__distributors_v_version_hero_image_rights_status";
  DROP TYPE "public"."enum__distributors_v_version_hero_image_rights_source_type";
  DROP TYPE "public"."enum_robot_series_hero_image_rights_status";
  DROP TYPE "public"."enum_robot_series_hero_image_rights_source_type";
  DROP TYPE "public"."enum__robot_series_v_version_hero_image_rights_status";
  DROP TYPE "public"."enum__robot_series_v_version_hero_image_rights_source_type";
  DROP TYPE "public"."enum_robots_hero_image_rights_status";
  DROP TYPE "public"."enum_robots_hero_image_rights_source_type";
  DROP TYPE "public"."enum__robots_v_version_hero_image_rights_status";
  DROP TYPE "public"."enum__robots_v_version_hero_image_rights_source_type";
  DROP TYPE "public"."enum_deployments_hero_image_rights_status";
  DROP TYPE "public"."enum_deployments_hero_image_rights_source_type";
  DROP TYPE "public"."enum__deployments_v_version_hero_image_rights_status";
  DROP TYPE "public"."enum__deployments_v_version_hero_image_rights_source_type";
  DROP TYPE "public"."enum_articles_hero_image_rights_status";
  DROP TYPE "public"."enum_articles_hero_image_rights_source_type";
  DROP TYPE "public"."enum__articles_v_version_hero_image_rights_status";
  DROP TYPE "public"."enum__articles_v_version_hero_image_rights_source_type";`)
}

/**
 * 手書き追記: このmigrationのdown()は新しい構造化列をdropし、旧JSON列を空のまま復元する
 * （構造化列へ既に入力された値をJSONへ書き戻すロジックは持たない）。`up()`適用後に
 * 実際に画像/ロゴが1件でも入力されていたら、silent data lossを避けるため一方向として拒否する
 * （`20260812_080919_date_only_content_fields_to_text.ts`と同じ考え方のguard）。
 */
async function assertNoImageDataEnteredSinceUp(db: MigrateDownArgs['db']): Promise<void> {
  await db.execute(sql`
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM "manufacturers" WHERE "logos_symbol_src" IS NOT NULL OR "logos_wordmark_src" IS NOT NULL OR "logos_combined_src" IS NOT NULL)
        OR EXISTS (SELECT 1 FROM "robots" WHERE "images_hero_src" IS NOT NULL OR "images_transparent_src" IS NOT NULL OR "images_side_src" IS NOT NULL OR "images_in_operation_src" IS NOT NULL OR "images_scale_src" IS NOT NULL OR "images_end_effector_src" IS NOT NULL OR "images_mobility_src" IS NOT NULL)
        OR EXISTS (SELECT 1 FROM "robot_series" WHERE "images_hero_src" IS NOT NULL OR "images_transparent_src" IS NOT NULL OR "images_side_src" IS NOT NULL OR "images_in_operation_src" IS NOT NULL OR "images_scale_src" IS NOT NULL OR "images_end_effector_src" IS NOT NULL OR "images_mobility_src" IS NOT NULL)
      THEN
        RAISE EXCEPTION 'Refusing to roll back: structured image/logo columns already contain data entered after the forward migration. Rolling back would silently drop it (down() restores the old JSON columns empty, it does not serialize the new columns back into JSON).';
      END IF;
    END $$;
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await assertNoImageDataEnteredSinceUp(db)
  await db.execute(sql`
   CREATE TYPE "public"."enum_manufacturers_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum_manufacturers_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum__manufacturers_v_version_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum__manufacturers_v_version_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum_distributors_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum_distributors_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum__distributors_v_version_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum__distributors_v_version_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum_robot_series_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum_robot_series_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum__robot_series_v_version_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum__robot_series_v_version_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum_robots_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum_robots_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum__robots_v_version_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum__robots_v_version_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum_deployments_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum_deployments_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum__deployments_v_version_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum__deployments_v_version_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum_articles_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum_articles_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  CREATE TYPE "public"."enum__articles_v_version_hero_image_rights_status" AS ENUM('own', 'licensed', 'commercial-permitted', 'reference-attributed', 'permission-requested', 'prototype-only', 'blocked');
  CREATE TYPE "public"."enum__articles_v_version_hero_image_rights_source_type" AS ENUM('own', 'manufacturer-official', 'partner-official', 'press-release', 'third-party', 'unknown');
  ALTER TABLE "manufacturers" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."enum_manufacturers_hero_image_rights_status" USING "hero_image_rights_status"::text::"public"."enum_manufacturers_hero_image_rights_status";
  ALTER TABLE "manufacturers" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."enum_manufacturers_hero_image_rights_source_type" USING "hero_image_rights_source_type"::text::"public"."enum_manufacturers_hero_image_rights_source_type";
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."enum__manufacturers_v_version_hero_image_rights_status" USING "version_hero_image_rights_status"::text::"public"."enum__manufacturers_v_version_hero_image_rights_status";
  ALTER TABLE "_manufacturers_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."enum__manufacturers_v_version_hero_image_rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."enum__manufacturers_v_version_hero_image_rights_source_type";
  ALTER TABLE "distributors" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."enum_distributors_hero_image_rights_status" USING "hero_image_rights_status"::text::"public"."enum_distributors_hero_image_rights_status";
  ALTER TABLE "distributors" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."enum_distributors_hero_image_rights_source_type" USING "hero_image_rights_source_type"::text::"public"."enum_distributors_hero_image_rights_source_type";
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."enum__distributors_v_version_hero_image_rights_status" USING "version_hero_image_rights_status"::text::"public"."enum__distributors_v_version_hero_image_rights_status";
  ALTER TABLE "_distributors_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."enum__distributors_v_version_hero_image_rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."enum__distributors_v_version_hero_image_rights_source_type";
  ALTER TABLE "robot_series" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."enum_robot_series_hero_image_rights_status" USING "hero_image_rights_status"::text::"public"."enum_robot_series_hero_image_rights_status";
  ALTER TABLE "robot_series" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."enum_robot_series_hero_image_rights_source_type" USING "hero_image_rights_source_type"::text::"public"."enum_robot_series_hero_image_rights_source_type";
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."enum__robot_series_v_version_hero_image_rights_status" USING "version_hero_image_rights_status"::text::"public"."enum__robot_series_v_version_hero_image_rights_status";
  ALTER TABLE "_robot_series_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."enum__robot_series_v_version_hero_image_rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."enum__robot_series_v_version_hero_image_rights_source_type";
  ALTER TABLE "robots" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."enum_robots_hero_image_rights_status" USING "hero_image_rights_status"::text::"public"."enum_robots_hero_image_rights_status";
  ALTER TABLE "robots" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."enum_robots_hero_image_rights_source_type" USING "hero_image_rights_source_type"::text::"public"."enum_robots_hero_image_rights_source_type";
  ALTER TABLE "_robots_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."enum__robots_v_version_hero_image_rights_status" USING "version_hero_image_rights_status"::text::"public"."enum__robots_v_version_hero_image_rights_status";
  ALTER TABLE "_robots_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."enum__robots_v_version_hero_image_rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."enum__robots_v_version_hero_image_rights_source_type";
  ALTER TABLE "deployments" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."enum_deployments_hero_image_rights_status" USING "hero_image_rights_status"::text::"public"."enum_deployments_hero_image_rights_status";
  ALTER TABLE "deployments" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."enum_deployments_hero_image_rights_source_type" USING "hero_image_rights_source_type"::text::"public"."enum_deployments_hero_image_rights_source_type";
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."enum__deployments_v_version_hero_image_rights_status" USING "version_hero_image_rights_status"::text::"public"."enum__deployments_v_version_hero_image_rights_status";
  ALTER TABLE "_deployments_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."enum__deployments_v_version_hero_image_rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."enum__deployments_v_version_hero_image_rights_source_type";
  ALTER TABLE "articles" ALTER COLUMN "hero_image_rights_status" SET DATA TYPE "public"."enum_articles_hero_image_rights_status" USING "hero_image_rights_status"::text::"public"."enum_articles_hero_image_rights_status";
  ALTER TABLE "articles" ALTER COLUMN "hero_image_rights_source_type" SET DATA TYPE "public"."enum_articles_hero_image_rights_source_type" USING "hero_image_rights_source_type"::text::"public"."enum_articles_hero_image_rights_source_type";
  ALTER TABLE "_articles_v" ALTER COLUMN "version_hero_image_rights_status" SET DATA TYPE "public"."enum__articles_v_version_hero_image_rights_status" USING "version_hero_image_rights_status"::text::"public"."enum__articles_v_version_hero_image_rights_status";
  ALTER TABLE "_articles_v" ALTER COLUMN "version_hero_image_rights_source_type" SET DATA TYPE "public"."enum__articles_v_version_hero_image_rights_source_type" USING "version_hero_image_rights_source_type"::text::"public"."enum__articles_v_version_hero_image_rights_source_type";
  ALTER TABLE "manufacturers" ADD COLUMN "logos" jsonb;
  ALTER TABLE "_manufacturers_v" ADD COLUMN "version_logos" jsonb;
  ALTER TABLE "robot_series" ADD COLUMN "images" jsonb;
  ALTER TABLE "_robot_series_v" ADD COLUMN "version_images" jsonb;
  ALTER TABLE "robots" ADD COLUMN "images" jsonb;
  ALTER TABLE "_robots_v" ADD COLUMN "version_images" jsonb;
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_src";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_alt";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_credit";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_source_url";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_rights_status";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_rights_source_type";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_rights_checked_at";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_rights_rights_holder";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_rights_license_url";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_rights_permission_note";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_symbol_aspect_ratio";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_src";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_alt";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_credit";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_source_url";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_rights_status";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_rights_source_type";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_rights_checked_at";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_rights_rights_holder";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_rights_license_url";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_rights_permission_note";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_wordmark_aspect_ratio";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_src";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_alt";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_credit";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_source_url";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_rights_status";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_rights_source_type";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_rights_checked_at";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_rights_rights_holder";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_rights_license_url";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_rights_permission_note";
  ALTER TABLE "manufacturers" DROP COLUMN "logos_combined_aspect_ratio";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_src";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_alt";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_credit";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_source_url";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_rights_status";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_rights_source_type";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_rights_checked_at";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_rights_rights_holder";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_rights_license_url";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_rights_permission_note";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_symbol_aspect_ratio";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_src";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_alt";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_credit";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_source_url";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_rights_status";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_rights_source_type";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_rights_checked_at";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_rights_rights_holder";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_rights_license_url";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_rights_permission_note";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_wordmark_aspect_ratio";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_src";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_alt";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_credit";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_source_url";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_rights_status";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_rights_source_type";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_rights_checked_at";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_rights_rights_holder";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_rights_license_url";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_rights_permission_note";
  ALTER TABLE "_manufacturers_v" DROP COLUMN "version_logos_combined_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_hero_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_transparent_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_side_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_in_operation_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_scale_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_end_effector_aspect_ratio";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_src";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_alt";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_credit";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_source_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_rights_status";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_rights_source_type";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_rights_checked_at";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_rights_rights_holder";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_rights_license_url";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_rights_permission_note";
  ALTER TABLE "robot_series" DROP COLUMN "images_mobility_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_hero_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_transparent_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_side_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_in_operation_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_scale_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_end_effector_aspect_ratio";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_src";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_alt";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_credit";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_source_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_rights_status";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_rights_source_type";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_rights_checked_at";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_rights_rights_holder";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_rights_license_url";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_rights_permission_note";
  ALTER TABLE "_robot_series_v" DROP COLUMN "version_images_mobility_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_hero_src";
  ALTER TABLE "robots" DROP COLUMN "images_hero_alt";
  ALTER TABLE "robots" DROP COLUMN "images_hero_credit";
  ALTER TABLE "robots" DROP COLUMN "images_hero_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_hero_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_hero_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_hero_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_hero_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_hero_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_hero_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_hero_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_src";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_alt";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_credit";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_transparent_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_side_src";
  ALTER TABLE "robots" DROP COLUMN "images_side_alt";
  ALTER TABLE "robots" DROP COLUMN "images_side_credit";
  ALTER TABLE "robots" DROP COLUMN "images_side_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_side_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_side_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_side_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_side_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_side_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_side_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_side_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_src";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_alt";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_credit";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_in_operation_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_scale_src";
  ALTER TABLE "robots" DROP COLUMN "images_scale_alt";
  ALTER TABLE "robots" DROP COLUMN "images_scale_credit";
  ALTER TABLE "robots" DROP COLUMN "images_scale_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_scale_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_scale_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_scale_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_scale_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_scale_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_scale_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_scale_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_src";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_alt";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_credit";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_end_effector_aspect_ratio";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_src";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_alt";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_credit";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_source_url";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_rights_status";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_rights_source_type";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_rights_checked_at";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_rights_rights_holder";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_rights_license_url";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_rights_permission_note";
  ALTER TABLE "robots" DROP COLUMN "images_mobility_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_hero_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_transparent_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_side_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_in_operation_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_scale_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_end_effector_aspect_ratio";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_src";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_alt";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_credit";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_source_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_rights_status";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_rights_source_type";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_rights_checked_at";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_rights_rights_holder";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_rights_license_url";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_rights_permission_note";
  ALTER TABLE "_robots_v" DROP COLUMN "version_images_mobility_aspect_ratio";
  DROP TYPE "public"."rights_status";
  DROP TYPE "public"."rights_source_type";`)
}
