import ReactMarkdown from 'react-markdown';
import { cn } from '@/lib/utils';
import { slugifyHeading } from '@/lib/markdownHeadings';

function childrenToText(children: React.ReactNode): string {
  if (typeof children === 'string') return children;
  if (Array.isArray(children)) return children.map(childrenToText).join('');
  if (children && typeof children === 'object' && 'props' in children) {
    const element = children as React.ReactElement<{ children?: React.ReactNode }>;
    return childrenToText(element.props.children);
  }
  return '';
}

// Renders body Markdown in the neutral-rectangle style of this site.
// h2/h3 receive id attrs generated by slugifyHeading so that ArticleToc anchor links work.
// Editorial rule: h2 text must be plain text and unique within the article.
export function Markdown({ source, className }: { source: string; className?: string }) {
  return (
    <div className={cn('max-w-[72ch] text-base leading-[1.75] text-foreground', className)}>
      <ReactMarkdown
        components={{
          h1: ({ children }) => (
            <h1 className="mt-6 mb-4 text-xl font-semibold text-foreground">{children}</h1>
          ),
          h2: ({ children }) => {
            const id = slugifyHeading(childrenToText(children));
            return (
              <h2
                id={id}
                className="scroll-mt-site-header mt-6 mb-3 text-lg font-semibold text-foreground"
              >
                {children}
              </h2>
            );
          },
          h3: ({ children }) => {
            const id = slugifyHeading(childrenToText(children));
            return (
              <h3
                id={id}
                className="scroll-mt-site-header mt-5 mb-2 text-base font-semibold text-foreground"
              >
                {children}
              </h3>
            );
          },
          p: ({ children }) => <p className="mb-4">{children}</p>,
          ul: ({ children }) => (
            <ul className="mb-4 list-disc space-y-1.5 pl-5">{children}</ul>
          ),
          ol: ({ children }) => (
            <ol className="mb-4 list-decimal space-y-1.5 pl-5">{children}</ol>
          ),
          li: ({ children }) => <li className="leading-[1.75]">{children}</li>,
          a: ({ children, href }) => (
            <a
              href={href}
              target={href?.startsWith('http') ? '_blank' : undefined}
              rel={href?.startsWith('http') ? 'noreferrer' : undefined}
              className="text-foreground underline hover:text-muted-foreground"
            >
              {children}
            </a>
          ),
          strong: ({ children }) => (
            <strong className="font-semibold text-foreground">{children}</strong>
          ),
          em: ({ children }) => <em className="italic">{children}</em>,
          blockquote: ({ children }) => (
            <blockquote className="my-4 border-l-4 border-border pl-4 italic text-muted-foreground">
              {children}
            </blockquote>
          ),
          code: ({ children }) => (
            <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-xs">{children}</code>
          ),
          hr: () => <hr className="my-6 border-border" />,
        }}
      >
        {source}
      </ReactMarkdown>
    </div>
  );
}
