export const uiText = {
  common: {
    home: 'ホーム',
    all: 'すべて',
    allTypes: 'すべての分類',
    allManufacturers: 'すべてのメーカー',
    allRegions: 'すべての地域',
    allStatus: 'すべてのステータス',
    clearAll: 'すべて解除',
    viewDetails: '詳細を見る',
    viewProfile: '詳細を見る',
    website: '公式サイト',
    contact: '問い合わせ',
    latest: '新着',
    source: '出典',
    credit: '画像',
    resources: '出典',
    overview: '概要',
    contents: '目次',
    updated: '更新',
    readingMinutes: (minutes: number) => `${minutes}分`,
    allIndustries: 'すべての業種',
    allTasks: 'すべてのタスク',
    results: (count: number, filtered: boolean) =>
      filtered ? `${count}件（絞り込み中）` : `${count}件`,
  },
  filters: {
    robotType: 'ロボット分類',
    manufacturer: 'メーカー',
    availability: '国内入手性',
    country: '所在地',
    companyType: '企業区分',
    status: 'ステータス',
    releaseStatus: '公開状態',
    guideStage: 'ガイド段階',
    guideTopics: 'ガイドトピック',
    reportType: '記事種別',
    reportTopics: '記事トピック',
    useCaseMode: '用途の探し方',
    industryTags: '業種タグ',
    taskTags: 'タスクタグ',
    industry: '業種',
    task: 'タスク',
  },
  robots: {
    breadcrumb: 'ロボット',
    title: 'ロボット一覧',
    activeModels: (count: number) => `${count}件の商用・実証機`,
    preReleaseModels: (count: number) => `${count}件の開発中・将来機種`,
    mainImageMissing: 'メイン画像なし',
    specifications: '仕様',
    technicalSpecifications: '技術仕様',
    decision: '導入判断',
    applications: '用途メモ',
    sortStage: '導入フェーズ順',
    sortJapan: '日本対応順',
    sortName: '名前順',
    sortLabel: '並び替え',
  },
  manufacturers: {
    breadcrumb: 'メーカー',
    title: 'メーカー一覧',
    profile: 'メーカープロフィール',
    factSheet: '基本情報',
    models: (count: number) => `${count}件の取扱機種`,
    sortJapan: '日本対応順',
    sortName: '名前順',
    sortFounded: '設立年順',
    sortLabel: '並び替え',
  },
  guides: {
    breadcrumb: 'ガイド',
    title: '導入ガイド',
    featured: '注目ガイド',
    read: 'ガイドを読む',
    relatedRobots: '関連機種',
    relatedUseCases: '関連用途',
    relatedRobotsCount: (count: number) => `${count}件の関連機種`,
    decisionSummary: '判断サマリ',
    compareCandidateRobots: '候補機種を比較する',
    relatedPaths: '関連導線',
    backToAll: 'ガイド一覧へ戻る',
    body: '本文',
    checklist: 'チェックリスト',
  },
  reports: {
    breadcrumb: 'レポート',
    title: 'レポート',
    featured: '注目レポート',
    read: 'レポートを読む',
    whyItMatters: 'なぜ重要か',
    keyTakeaways: '要点',
  },
  useCases: {
    breadcrumb: '用途',
    title: '用途から探す',
    featured: '注目の適用領域',
    all: 'すべての用途',
    candidateRobots: (count: number) => `${count}件の候補機種`,
    atAGlance: '要点',
  },
  compare: {
    breadcrumb: '比較',
    title: '比較',
    manufacturers: 'メーカー',
    comparisonSheet: (count: number, max: number) => `比較シート（${count}/${max}）`,
    favorites: 'お気に入り',
    compare: '比較する',
    keySpecs: '主要スペック',
    decisionFactors: '導入判断',
    strengths: '強み',
    constraints: '制約',
    bestFit: '向く用途',
    notFit: '向かない用途',
    deploymentStage: '提供段階',
    japanAvailability: '国内入手性',
    procurement: '調達形態',
    price: '参考価格',
    remove: '比較から外す',
    addFavorite: 'お気に入りに追加',
    removeFavorite: 'お気に入りから外す',
  },
} as const;
