export const uiText = {
  common: {
    home: 'ホーム',
    compareAllCandidates: '候補ロボットを一括比較',
    all: 'すべて',
    allTypes: 'すべての分類',
    allManufacturers: 'すべてのメーカー',
    allRegions: 'すべての地域',
    allStatus: 'すべてのステータス',
    clearAll: 'すべて解除',
    website: '公式サイト',
    contact: '問い合わせ',
    latest: '新着',
    source: '出典',
    credit: '画像',
    resources: '出典',
    overview: '概要',
    contents: '目次',
    updated: '更新',
    readingMinutes: (minutes: number) => `${minutes}分`,
    allIndustries: 'すべての業種',
    allTasks: 'すべてのタスク',
    allThemes: 'すべてのテーマ',
    results: (count: number, filtered: boolean) =>
      filtered ? `${count}件（絞り込み中）` : `${count}件`,
  },
  controls: {
    clearSearch: '検索をクリア',
    dropdownEmpty: '該当する選択肢がありません',
    dropdownSearchAria: (label: string) => `${label}の選択肢を検索`,
    dropdownSearchPlaceholder: (label: string) => `${label}を検索`,
  },
  searchPlaceholders: {
    robots: 'ロボット名・メーカー・用途キーワードで検索',
    manufacturers: 'メーカー名・地域・取扱ロボットで検索',
    reports: 'タイトル・トピック・キーワードで検索',
    useCases: '自動化したい作業は？',
  },
  emptyStates: {
    robots: '条件に合うロボットがありません。フィルタを調整してください。',
    manufacturers: '条件に合うメーカーがありません。',
    reports: '条件に合う記事がありません。',
    useCases: '条件に合う用途がありません。',
    sources: '出典は本文作成時に追加予定です。',
  },
  filters: {
    robotType: 'ロボット分類',
    manufacturer: 'メーカー',
    availability: '国内入手性',
    country: '所在地',
    region: '地域',
    consultationRoute: '相談ルート',
    companyType: '企業区分',
    status: 'ステータス',
    releaseStatus: '公開状態',
    articleType: '記事種別',
    reportTopics: '記事トピック',
    industry: '業種',
    task: 'タスク',
    theme: 'テーマ',
    keywordSearch: 'キーワード検索',
  },
  robots: {
    breadcrumb: 'ロボット',
    title: 'ロボット',
    description: '業種・メーカー・国内入手性で絞り込み、現場に合う候補を探せます。',
    activeSection: (count: number) => `販売中・限定販売（${count}件）`,
    preReleaseSection: (count: number) => `開発中・プロトタイプ（${count}件）`,
    mainImageMissing: '公式画像申請中',
    imageRequested: 'Official Image Requested',
    specifications: '仕様',
    technicalSpecifications: '技術仕様',
    decision: '導入判断',
    applications: '用途・適用範囲',
    bestFit: '向く用途',
    constraints: '制約・向かない用途',
    notFit: '不向きな現場',
    archivedNotice: '提供終了：',
    archivedDescription: 'この機種は現行ラインアップではありません。',
    successor: '後継機',
    basicSpecs: '基本スペック',
    deploymentStage: '導入段階',
    japanAvailability: '日本での入手性',
    toManufacturerSite: 'メーカーサイトへ',
    checkOnComparePage: '比較ページで確認',
  },
  manufacturers: {
    breadcrumb: 'メーカー',
    title: 'メーカー',
    description: '地域と国内の取り扱い状況から、日本で検討しやすいメーカーを確認できます。',
    factSheet: '基本情報',
    sectionNavAria: 'メーカー詳細セクション',
    robotsSection: '取扱ロボット',
    relatedReports: '関連記事',
    contactPanel: '相談導線',
    officialContact: '公式窓口へ',
    consultDeploid: 'Deploidに相談',
    externalWebsite: '公式サイトを見る',
    location: '所在地',
    founded: '設立',
    companyType: '企業区分',
    companyStatus: '会社ステータス',
    japanPresence: '日本体制',
    consultationRoute: '相談ルート',
    domesticDistributors: '国内代理店',
    handledRobots: '取扱ロボット',
    lastUpdated: '最終更新',
    models: (count: number) => `${count}件の取扱ロボット`,
  },
  reports: {
    breadcrumb: '記事',
    /** メーカー解説（manufacturer-guide）テンプレート専用のUI文言 */
    guideLineupRobot: '機体',
    guideLineupRole: '位置づけ',
    guideLineupPrice: '価格目安',
    guideFaqPrefix: 'Q. ',
    title: '記事',
    featured: '注目記事',
    read: '記事を読む',
    whyItMatters: 'なぜ重要か',
    keyTakeaways: '要点',
    body: '本文',
    relatedInfo: '関連情報',
    relatedRobots: '関連ロボット',
    relatedManufacturers: '関連メーカー',
    relatedUseCases: '関連用途',
    sidebarPressContactTitle: '情報提供・取材相談',
    sidebarPressContactDescription: '導入事例や一次情報の提供、取材のご相談はこちら。',
    sidebarContactCta: 'お問い合わせ',
    sidebarToolsTitle: '関連ツール',
    sidebarToolFindRobots: 'ロボットを探す',
    sidebarToolCompare: '機種を比較する',
    tags: 'タグ',
  },
  useCases: {
    breadcrumb: '用途から探す',
    title: '用途から探す',
    description: '産業・現場タスクからヒューマノイドの実適用シーンを探す。実導入事例の有無を明示しています。',
    featured: '注目の適用領域',
    all: 'すべての用途',
    candidateRobots: (count: number) => `${count}件の候補ロボット`,
    industryTabsAriaLabel: '産業で絞り込む',
    industryTasksHeading: (label: string) => `${label}のタスク`,
    clearFilterAria: 'フィルターをクリア',
    detail: '詳細',
    atAGlance: '要点',
    deployments: '導入事例',
    deploymentsSectionTitle: '実際の導入事例',
    whyItMatters: 'なぜ重要か',
    considerations: '論点',
    considerationsSectionTitle: '導入検討の論点（要点）',
    detailSectionAria: '用途詳細セクション',
    wherefits: '向く条件',
    whereDoesNotFit: '向かない条件',
    mustBeTrue: '成立条件',
    candidateRobotsLabel: '候補ロボット',
    related: '関連記事',
    consultation: '導入相談',
    consultationDescription: 'どの用途から検討すべきか整理したい場合はご相談ください。',
    consultationCta: '相談する',
    environmentRequirements: '環境要件',
    whyHardToday: 'なぜ今は難しいか',
    japanDeploymentConditions: '日本での導入条件',
    deploymentSource: (publisher: string) => `出典：${publisher}`,
    evidenceSummary: {
      deployment: '実導入事例あり',
    },
  },
  compare: {
    breadcrumb: '比較',
    title: '比較',
    desktopDescription: '左のメニューからロボットを選んで比較します。右パネルで気になるロボットをお気に入り登録できます。',
    mobileDescription: 'メーカーを選んでロボットを追加してください。',
    manufacturers: 'メーカー',
    selectManufacturer: 'メーカーを選択',
    manufacturerEmpty: 'このメーカーのロボットデータはありません。',
    menuSearchPlaceholder: '機体名・メーカー名で検索',
    comparisonSheet: (count: number, max: number) => `比較シート（${count}/${max}）`,
    favorites: 'お気に入り',
    compare: '比較する',
    keySpecs: '主要スペック',
    decisionFactors: '導入判断',
    strengths: '強み',
    constraints: '制約',
    bestFit: '向く用途',
    notFit: '向かない用途',
    deploymentStage: '提供段階',
    japanAvailability: '国内入手性',
    procurement: '調達形態',
    price: '参考価格',
    remove: '比較から外す',
    addFavorite: 'お気に入りに追加',
    removeFavorite: 'お気に入りから外す',
  },
  contact: {
    breadcrumb: 'お問い合わせ',
    title: 'お問い合わせ',
    successTitle: '送信しました',
    successMessage: 'お問い合わせありがとうございます。内容を確認のうえ折り返しご連絡します。',
    formPending: 'お問い合わせフォームは現在準備中です。設定完了後に送信できます。',
    name: 'お名前',
    company: '会社名・組織名',
    email: 'メールアドレス',
    inquiryType: 'ご相談の種別',
    message: '内容',
    required: '（必須）',
    submit: '送信する',
    submitting: '送信中…',
    setupPending: 'フォーム設定待ち',
  },
  favorites: {
    empty: 'お気に入りはまだありません',
    emptySub: 'カードの星アイコンでお気に入りに追加できます',
    ariaAdd: (name: string) => `${name} をお気に入りに追加する`,
    ariaRemove: (name: string) => `${name} をお気に入りから外す`,
    payload: 'ペイロード',
    runtime: '稼働時間',
    runtimeValue: (min: number) => `約${min} 分`,
  },
  comparison: {
    emptyTitle: '比較シートにロボットがありません。',
    emptyDescription: '左メニューから追加できます。',
    clearAria: '比較シートを空にする',
    addAria: (name: string) => `${name}を比較に追加する`,
    addToSheet: '追加',
    removeAria: (name: string) => `${name}を比較から外す`,
    reorderAria: (name: string) => `${name}の比較順を並び替える`,
    reorderHint: 'ドラッグまたはキーボードで並び替え',
    viewToggleAria: '表示の切替',
    viewVisual: 'ビジュアル',
    viewSpecs: 'スペック',
    shareLink: 'この比較を共有',
    shareCopied: 'リンクをコピーしました',
    shareFailed: 'コピーできませんでした。アドレスバーのURLを共有してください',
    relatedTools: '関連ツール',
    contactConsultation: '情報提供・取材相談',
    contactDescription: '導入事例や一次情報の提供、取材のご相談はこちら。',
    coreVariables: '基本スペック',
    detailedData: '詳細データ',
    japanSupport: '国内対応',
    dimensions: '外形寸法',
    tabBasic: '基本',
    tabDetailed: '詳細',
    distributor: '代理店',
    detailsLabel: '詳細',
    detailsAria: (name: string) => `${name}の詳細を確認する`,
    closeDetail: '詳細を閉じる',
    viewRobotPage: 'ロボット詳細ページへ',
  },
  home: {
    worldMap: {
      kicker: 'JAPAN HUMANOID PORTAL',
      heading: 'ヒューマノイド\n導入検討するあなたの\n最初の一歩。',
      subcopy:
        '主要なロボットのスペック、性能比較から、導入リスクの評価まで。\n導入に必要な「実装プロセス」のすべてをまとめた実践ガイドです。',
      ctaRobots: 'ロボット一覧',
      deployments: 'Deployments',
      memberCount: (count: number) => `${count}社`,
      overflowCount: (count: number) => `+${count}`,
      clusterAriaLabel: (regionName: string, count: number) => `${regionName}の${count}社の一覧を見る`,
      singleAriaLabel: (manufacturerName: string, regionName: string) =>
        `${manufacturerName}（${regionName}）の詳細を見る`,
    },
  },
} as const;
